### ISSUE TITLE
please tag a new version and release a new gem

### ISSUE THREAD

**Issue by boutil** [chrisk/fakeweb#47]
Hi,

The last tagged release was 4 years ago and a lot of code has changed since then. Could you please tag a new version and release a new gem?

Thanks in advance.

Cédric

**Comment by betesh** [comment]
duplicates #57

**Comment by chrisk** [comment]
Hello, thanks for opening this. This issue was first, but there's been a bunch of discussion in #57, so I'm going to close this in favor of that one. There will be a point release to restore compatibility with all mainstream versions of Ruby soon.
